import { supabase } from "@/lib/supabaseClient";
import "./../globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/public/Header";
import Footer from "@/components/public/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
