import "./../globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/public/Header";
import Footer from "@/components/public/Footer";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient({ cookies });
  const { data: navigation } = await supabase.from("navigation").select("*");

  const { data: settings } = await supabase.from("settings").select("*");

  let reMappedSettings = settings!.reduce((acc, obj) => {
    acc[obj.key] = obj;
    return acc;
  }, {});

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header navigation={navigation} settings={reMappedSettings} />

        {children}
        <Footer navigation={navigation} settings={reMappedSettings} />
      </body>
    </html>
  );
}
